# Auto-generated from Move_SILVERWIND.json — do not edit by hand.
module SilverWindAnimImport
  module AnimationData
    SLOT = 243
    NAME = "Move:SILVERWIND"

    def self.build_animation
      anim = PBAnimation.new
      anim.name = "Move:SILVERWIND"
      anim.graphic = "Heal5"
      anim.hue = 20
      anim.position = 1
      anim.instance_variable_set(:@speed, 20)
      anim.array.clear
      anim.timing.clear

      t = PBAnimTiming.new(0)
      t.frame = 0
      t.name = "Wind8"
      t.volume = 80
      t.pitch = 100
      anim.timing << t

      t = PBAnimTiming.new(1)
      t.frame = 0
      t.colorRed = 160
      t.colorGreen = 255
      t.colorBlue = 160
      t.colorAlpha = 0
      t.opacity = 0
      anim.timing << t

      t = PBAnimTiming.new(2)
      t.frame = 0
      t.colorRed = 160
      t.colorGreen = 255
      t.colorBlue = 160
      t.colorAlpha = 0
      t.opacity = 72
      t.duration = 5
      anim.timing << t

      t = PBAnimTiming.new(2)
      t.frame = 13
      t.colorRed = 160
      t.colorGreen = 255
      t.colorBlue = 160
      t.colorAlpha = 0
      t.opacity = 0
      t.duration = 5
      anim.timing << t

      t = PBAnimTiming.new(1)
      t.frame = 17
      t.colorRed = 160
      t.colorGreen = 255
      t.colorBlue = 160
      t.colorAlpha = 0
      t.opacity = 0
      anim.timing << t

      frame = []
      c = pbCreateCel(128, 224, -1, 2)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[0] = c
      c = pbCreateCel(384, 96, -2, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[1] = c
      c = pbCreateCel(168, -10, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[2] = c
      anim.array[0] = frame

      frame = []
      c = pbCreateCel(128, 224, -1, 2)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[0] = c
      c = pbCreateCel(384, 96, -2, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[1] = c
      c = pbCreateCel(208, 22, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[2] = c
      c = pbCreateCel(96, 30, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[3] = c
      c = pbCreateCel(136, -42, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[4] = c
      anim.array[1] = frame

      frame = []
      c = pbCreateCel(128, 224, -1, 2)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[0] = c
      c = pbCreateCel(384, 96, -2, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[1] = c
      c = pbCreateCel(248, 62, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[2] = c
      c = pbCreateCel(264, -42, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[3] = c
      c = pbCreateCel(152, 94, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[4] = c
      c = pbCreateCel(192, 6, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[5] = c
      c = pbCreateCel(104, 6, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[6] = c
      anim.array[2] = frame

      frame = []
      c = pbCreateCel(128, 224, -1, 2)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[0] = c
      c = pbCreateCel(384, 96, -2, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[1] = c
      c = pbCreateCel(304, 102, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[2] = c
      c = pbCreateCel(312, -2, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[3] = c
      c = pbCreateCel(216, 150, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[4] = c
      c = pbCreateCel(248, 54, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[5] = c
      c = pbCreateCel(160, 70, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[6] = c
      c = pbCreateCel(240, -42, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[7] = c
      c = pbCreateCel(96, -10, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[8] = c
      c = pbCreateCel(216, 38, 0, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 50
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[9] = c
      anim.array[3] = frame

      frame = []
      c = pbCreateCel(128, 224, -1, 2)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[0] = c
      c = pbCreateCel(384, 96, -2, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[1] = c
      c = pbCreateCel(368, 142, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[2] = c
      c = pbCreateCel(368, 46, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[3] = c
      c = pbCreateCel(296, 198, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[4] = c
      c = pbCreateCel(312, 102, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[5] = c
      c = pbCreateCel(224, 134, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[6] = c
      c = pbCreateCel(304, -10, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[7] = c
      c = pbCreateCel(128, 46, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[8] = c
      c = pbCreateCel(168, -26, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[9] = c
      c = pbCreateCel(408, -42, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[10] = c
      c = pbCreateCel(216, 38, 1, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 50
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[11] = c
      anim.array[4] = frame

      frame = []
      c = pbCreateCel(128, 224, -1, 2)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[0] = c
      c = pbCreateCel(384, 96, -2, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[1] = c
      c = pbCreateCel(440, 182, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[2] = c
      c = pbCreateCel(448, 86, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[3] = c
      c = pbCreateCel(368, 238, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[4] = c
      c = pbCreateCel(384, 142, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[5] = c
      c = pbCreateCel(280, 190, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[6] = c
      c = pbCreateCel(384, 30, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[7] = c
      c = pbCreateCel(176, 118, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[8] = c
      c = pbCreateCel(232, 38, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[9] = c
      c = pbCreateCel(104, 86, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[10] = c
      c = pbCreateCel(496, -10, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[11] = c
      c = pbCreateCel(424, 6, 10, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 50
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[12] = c
      c = pbCreateCel(184, -34, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[13] = c
      c = pbCreateCel(88, 166, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[14] = c
      c = pbCreateCel(96, 6, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[15] = c
      c = pbCreateCel(376, -50, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[16] = c
      c = pbCreateCel(184, 142, 0, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 50
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[17] = c
      anim.array[5] = frame

      frame = []
      c = pbCreateCel(128, 224, -1, 2)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[0] = c
      c = pbCreateCel(384, 96, -2, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[1] = c
      c = pbCreateCel(504, 214, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[2] = c
      c = pbCreateCel(520, 110, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[3] = c
      c = pbCreateCel(448, 166, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[4] = c
      c = pbCreateCel(344, 230, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[5] = c
      c = pbCreateCel(480, 70, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[6] = c
      c = pbCreateCel(224, 174, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[7] = c
      c = pbCreateCel(296, 94, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[8] = c
      c = pbCreateCel(152, 150, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[9] = c
      c = pbCreateCel(576, 30, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[10] = c
      c = pbCreateCel(456, 134, 9, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 50
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[11] = c
      c = pbCreateCel(424, 6, 11, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 50
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[12] = c
      c = pbCreateCel(136, 230, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[13] = c
      c = pbCreateCel(264, 6, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[14] = c
      c = pbCreateCel(148, 53, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[15] = c
      c = pbCreateCel(440, -2, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[16] = c
      c = pbCreateCel(184, 142, 1, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 50
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[17] = c
      c = pbCreateCel(33, -1, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[18] = c
      anim.array[6] = frame

      frame = []
      c = pbCreateCel(128, 224, -1, 2)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[0] = c
      c = pbCreateCel(384, 96, -2, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[1] = c
      c = pbCreateCel(560, 238, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[2] = c
      c = pbCreateCel(608, 142, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[3] = c
      c = pbCreateCel(512, 206, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[4] = c
      c = pbCreateCel(576, 102, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[5] = c
      c = pbCreateCel(272, 230, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[6] = c
      c = pbCreateCel(376, 158, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[7] = c
      c = pbCreateCel(192, 214, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[8] = c
      c = pbCreateCel(664, 78, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[9] = c
      c = pbCreateCel(336, 110, 11, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 50
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[10] = c
      c = pbCreateCel(456, 134, 10, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 50
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[11] = c
      c = pbCreateCel(344, 54, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[12] = c
      c = pbCreateCel(208, 142, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[13] = c
      c = pbCreateCel(520, 30, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[14] = c
      anim.array[7] = frame

      frame = []
      c = pbCreateCel(128, 224, -1, 2)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[0] = c
      c = pbCreateCel(384, 96, -2, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[1] = c
      c = pbCreateCel(576, 166, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[2] = c
      c = pbCreateCel(576, 230, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[3] = c
      c = pbCreateCel(656, 134, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[4] = c
      c = pbCreateCel(456, 222, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[5] = c
      c = pbCreateCel(488, 134, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[6] = c
      c = pbCreateCel(336, 110, 11, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 50
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[7] = c
      c = pbCreateCel(264, 222, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[8] = c
      c = pbCreateCel(624, 78, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[9] = c
      anim.array[8] = frame

      frame = []
      c = pbCreateCel(128, 224, -1, 2)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[0] = c
      c = pbCreateCel(384, 96, -2, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[1] = c
      c = pbCreateCel(168, -10, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[2] = c
      c = pbCreateCel(620, 162, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[3] = c
      c = pbCreateCel(626, 238, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[4] = c
      c = pbCreateCel(712, 128, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[5] = c
      c = pbCreateCel(500, 224, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[6] = c
      c = pbCreateCel(538, 144, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[7] = c
      c = pbCreateCel(320, 214, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[8] = c
      c = pbCreateCel(668, 82, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[9] = c
      anim.array[9] = frame

      frame = []
      c = pbCreateCel(128, 224, -1, 2)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[0] = c
      c = pbCreateCel(384, 96, -2, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[1] = c
      c = pbCreateCel(96, 30, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[2] = c
      c = pbCreateCel(212, -2, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[3] = c
      c = pbCreateCel(670, 156, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[4] = c
      c = pbCreateCel(682, 240, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[5] = c
      c = pbCreateCel(112, 62, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[6] = c
      c = pbCreateCel(550, 216, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[7] = c
      c = pbCreateCel(594, 148, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[8] = c
      c = pbCreateCel(364, 212, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[9] = c
      c = pbCreateCel(718, 88, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[10] = c
      anim.array[10] = frame

      frame = []
      c = pbCreateCel(128, 224, -1, 2)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[0] = c
      c = pbCreateCel(384, 96, -2, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[1] = c
      c = pbCreateCel(136, -42, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[2] = c
      c = pbCreateCel(140, 24, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[3] = c
      c = pbCreateCel(262, 0, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[4] = c
      c = pbCreateCel(86, 46, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[5] = c
      c = pbCreateCel(123, 75, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[6] = c
      c = pbCreateCel(162, 66, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[7] = c
      c = pbCreateCel(606, 214, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[8] = c
      c = pbCreateCel(638, 154, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[9] = c
      c = pbCreateCel(414, 208, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[10] = c
      c = pbCreateCel(116, 80, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[11] = c
      anim.array[11] = frame

      frame = []
      c = pbCreateCel(128, 224, -1, 2)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[0] = c
      c = pbCreateCel(384, 96, -2, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[1] = c
      c = pbCreateCel(104, 6, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[2] = c
      c = pbCreateCel(180, -40, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[3] = c
      c = pbCreateCel(190, 34, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[4] = c
      c = pbCreateCel(318, -8, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[5] = c
      c = pbCreateCel(130, 50, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[6] = c
      c = pbCreateCel(173, 73, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[7] = c
      c = pbCreateCel(218, 72, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[8] = c
      c = pbCreateCel(650, 210, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[9] = c
      c = pbCreateCel(688, 162, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[10] = c
      c = pbCreateCel(470, 202, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[11] = c
      c = pbCreateCel(160, 82, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[12] = c
      anim.array[12] = frame

      frame = []
      c = pbCreateCel(128, 224, -1, 2)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[0] = c
      c = pbCreateCel(384, 96, -2, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[1] = c
      c = pbCreateCel(152, 94, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[2] = c
      c = pbCreateCel(148, 16, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[3] = c
      c = pbCreateCel(230, -48, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[4] = c
      c = pbCreateCel(246, 38, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[5] = c
      c = pbCreateCel(362, -10, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[6] = c
      c = pbCreateCel(180, 56, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[7] = c
      c = pbCreateCel(229, 69, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[8] = c
      c = pbCreateCel(262, 80, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[9] = c
      c = pbCreateCel(700, 204, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[10] = c
      c = pbCreateCel(138, 106, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[11] = c
      c = pbCreateCel(514, 212, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[12] = c
      c = pbCreateCel(210, 74, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[13] = c
      anim.array[13] = frame

      frame = []
      c = pbCreateCel(128, 224, -1, 2)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[0] = c
      c = pbCreateCel(384, 96, -2, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[1] = c
      c = pbCreateCel(128, 46, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[2] = c
      c = pbCreateCel(196, 86, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[3] = c
      c = pbCreateCel(198, 20, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[4] = c
      c = pbCreateCel(286, -50, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[5] = c
      c = pbCreateCel(290, 44, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[6] = c
      c = pbCreateCel(412, -14, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[7] = c
      c = pbCreateCel(236, 64, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[8] = c
      c = pbCreateCel(273, 63, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[9] = c
      c = pbCreateCel(312, 82, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[10] = c
      c = pbCreateCel(149, -21, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[11] = c
      c = pbCreateCel(182, 98, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[12] = c
      c = pbCreateCel(564, 216, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[13] = c
      c = pbCreateCel(266, 72, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[14] = c
      anim.array[14] = frame

      frame = []
      c = pbCreateCel(128, 224, -1, 2)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[0] = c
      c = pbCreateCel(384, 96, -2, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[1] = c
      c = pbCreateCel(168, -26, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[2] = c
      c = pbCreateCel(172, 50, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[3] = c
      c = pbCreateCel(246, 84, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[4] = c
      c = pbCreateCel(254, 26, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[5] = c
      c = pbCreateCel(330, -54, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[6] = c
      c = pbCreateCel(340, 52, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[7] = c
      c = pbCreateCel(468, -20, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[8] = c
      c = pbCreateCel(280, 66, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[9] = c
      c = pbCreateCel(323, 73, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[10] = c
      c = pbCreateCel(368, 74, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[11] = c
      c = pbCreateCel(193, -17, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[12] = c
      c = pbCreateCel(232, 96, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[13] = c
      c = pbCreateCel(620, 222, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[14] = c
      c = pbCreateCel(310, 68, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[15] = c
      anim.array[15] = frame

      frame = []
      c = pbCreateCel(128, 224, -1, 2)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[0] = c
      c = pbCreateCel(384, 96, -2, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[1] = c
      c = pbCreateCel(96, -10, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[2] = c
      c = pbCreateCel(212, -28, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[3] = c
      c = pbCreateCel(222, 56, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[4] = c
      c = pbCreateCel(302, 80, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[5] = c
      c = pbCreateCel(298, 34, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[6] = c
      c = pbCreateCel(380, -60, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[7] = c
      c = pbCreateCel(396, 54, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[8] = c
      c = pbCreateCel(512, -10, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[9] = c
      c = pbCreateCel(330, 58, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[10] = c
      c = pbCreateCel(379, 77, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[11] = c
      c = pbCreateCel(412, 72, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[12] = c
      c = pbCreateCel(243, -11, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[13] = c
      c = pbCreateCel(288, 92, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[14] = c
      c = pbCreateCel(664, 230, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[15] = c
      c = pbCreateCel(360, 62, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[16] = c
      anim.array[16] = frame

      frame = []
      c = pbCreateCel(128, 224, -1, 2)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[0] = c
      c = pbCreateCel(384, 96, -2, 1)
      c[AnimFrame::ZOOMX] = 100
      c[AnimFrame::ZOOMY] = 100
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 1
      c[AnimFrame::PRIORITY] = 1
      frame[1] = c
      c = pbCreateCel(184, -34, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[2] = c
      c = pbCreateCel(140, -4, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[3] = c
      c = pbCreateCel(262, -32, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[4] = c
      c = pbCreateCel(278, 64, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[5] = c
      c = pbCreateCel(346, 74, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[6] = c
      c = pbCreateCel(348, 36, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[7] = c
      c = pbCreateCel(436, -50, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[8] = c
      c = pbCreateCel(440, 46, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[9] = c
      c = pbCreateCel(562, -6, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[10] = c
      c = pbCreateCel(386, 56, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[11] = c
      c = pbCreateCel(423, 83, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[12] = c
      c = pbCreateCel(462, 68, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[13] = c
      c = pbCreateCel(299, -3, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[14] = c
      c = pbCreateCel(332, 86, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[15] = c
      c = pbCreateCel(714, 232, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[16] = c
      c = pbCreateCel(416, 72, 12, 1)
      c[AnimFrame::ZOOMX] = 20
      c[AnimFrame::ZOOMY] = 20
      c[AnimFrame::ANGLE] = 0
      c[AnimFrame::MIRROR] = 0
      c[AnimFrame::OPACITY] = 255
      c[AnimFrame::BLENDTYPE] = 0
      c[AnimFrame::VISIBLE] = 1
      c[AnimFrame::LOCKED] = 0
      c[AnimFrame::PRIORITY] = 1
      frame[17] = c
      anim.array[17] = frame

      return anim
    end
  end
end