#!/usr/bin/env python3
"""
Export PBS game data to Pokemon Showdown dex JS bundles for the local website.

Reads PBS/pokemon*.txt, moves.txt, abilities.txt, encounters.txt, map_metadata.txt
and writes website/showdown-dex/data/*.js

Usage:
  python tools/export_showdown_dex.py
  python tools/export_showdown_dex.py --out website/showdown-dex/data
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PBS = ROOT / "PBS"
DEFAULT_OUT = ROOT / "website" / "showdown-dex" / "data"

sys.path.insert(0, str(ROOT / "tools"))
from export_sprite_list import (  # noqa: E402
    FORM_SUFFIX,
    merge_form,
    parse_pbs_forms,
    parse_pbs_species_files,
    showdown_id,
    species_slug,
    stats_from,
    title_type,
    types_from,
)

GENDER_MAP = {
    "AlwaysMale": "M",
    "AlwaysFemale": "F",
    "Genderless": "N",
    "FemaleOneEighth": {"M": 0.875, "F": 0.125},
    "FemaleOneFourth": {"M": 0.75, "F": 0.25},
    "Female50Percent": {"M": 0.5, "F": 0.5},
    "FemaleThreeFourths": {"M": 0.25, "F": 0.75},
    "FemaleSevenEighths": {"M": 0.125, "F": 0.875},
}

EGG_GROUP_MAP = {
    "MONSTER": "Monster",
    "WATER1": "Water 1",
    "BUG": "Bug",
    "FLYING": "Flying",
    "FIELD": "Field",
    "FAIRY": "Fairy",
    "GRASS": "Grass",
    "HUMANLIKE": "Human-Like",
    "WATER3": "Water 3",
    "MINERAL": "Mineral",
    "AMORPHOUS": "Amorphous",
    "WATER2": "Water 2",
    "DITTO": "Ditto",
    "DRAGON": "Dragon",
    "UNDISCOVERED": "Undiscovered",
}

LAND_ENC_TYPES = {
    "Land", "LandMorning", "LandDay", "LandAfternoon", "LandEvening", "LandNight",
    "Cave", "RockSmash", "BugContest", "HeadbuttLow", "HeadbuttHigh", "PokeRadar",
}
FISH_ENC_TYPES = {"OldRod", "GoodRod", "SuperRod"}
WATER_ENC_TYPES = {"Water", "Surf"}


def to_id(text: str) -> str:
    return re.sub(r"[^a-z0-9]", "", text.lower())


def title_word(word: str) -> str:
    if not word:
        return word
    special = {"HP": "HP", "SP": "Sp"}
    up = word.upper()
    if up in special:
        return special[up]
    if word.isupper() and len(word) > 3:
        return word.title()
    return word[0].upper() + word[1:].lower() if word else word


def title_name(raw: str) -> str:
    parts = re.split(r"([ -])", raw.strip())
    return "".join(title_word(p) if p not in (" ", "-") else p for p in parts)


def es3_stringify(obj) -> str:
    buf = json.dumps(obj, ensure_ascii=True, separators=(",", ":"))
    reserved = {"return", "new", "delete"}

    def repl(match):
        key = match.group(1)
        if key in reserved:
            return match.group(0)
        return f"{key}:"

    return re.sub(r'"([A-Za-z][A-Za-z0-9]*)":', repl, buf)


def write_js(path: Path, export_name: str, obj) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = f"// Auto-generated by tools/export_showdown_dex.py — do not edit\n\nexports.{export_name} = {es3_stringify(obj)};\n"
    path.write_text(body, encoding="utf-8")
    print(f"wrote {path} ({path.stat().st_size // 1024} KB)")


def parse_pbs_blocks(path: Path):
    """Yield (section_id, dict) from a generic PBS file."""
    current_id = None
    current = None
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r"^\[([^\]]+)\]$", line)
        if m:
            if current_id is not None:
                yield current_id, current or {}
            current_id = m.group(1)
            current = {}
            continue
        if current is None:
            continue
        m = re.match(r"^(\w+)\s*=\s*(.*)$", line)
        if m:
            current[m.group(1)] = m.group(2).strip()
    if current_id is not None:
        yield current_id, current or {}


def parse_map_metadata():
    maps = {}
    map_id = None
    for raw in (PBS / "map_metadata.txt").read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("# See"):
            continue
        m = re.match(r"^\[(\d+)\]", line)
        if m:
            map_id = int(m.group(1))
            maps[map_id] = f"Map {map_id:03d}"
            continue
        if map_id is None:
            continue
        m = re.match(r"^Name\s*=\s*(.*)$", line)
        if m:
            name = m.group(1).strip()
            if name:
                maps[map_id] = name.replace("\\PN", "Player")
    return maps


def parse_evolutions(raw: str):
    if not raw:
        return []
    parts = [p.strip() for p in raw.split(",") if p.strip()]
    evos = []
    i = 0
    while i + 2 < len(parts):
        target = parts[i]
        method = parts[i + 1]
        param = parts[i + 2]
        evos.append({"species": target, "method": method, "param": param})
        i += 3
    return evos


def display_name(species_id: str, data: dict, form_name: str, is_form: bool) -> str:
    base_name = data.get("Name", title_name(species_id))
    if not is_form or not form_name:
        return base_name
    # Match Showdown hyphenated form names where possible
    if form_name.startswith("Mega ") and form_name.endswith(" X"):
        return f"{base_name}-Mega-X"
    if form_name.startswith("Mega ") and form_name.endswith(" Y"):
        return f"{base_name}-Mega-Y"
    if form_name.startswith("Mega "):
        return f"{base_name}-Mega"
    if form_name.endswith(" Forme") or form_name.endswith(" Form"):
        short = form_name.replace(" Forme", "").replace(" Form", "")
        if short in ("Alolan", "Galarian", "Hisuian", "Paldean"):
            return f"{base_name}-{short[:-2] if short.endswith('n') else short}"
        return f"{base_name}-{short}"
    if form_name in ("Alolan", "Galarian", "Hisuian", "Paldean"):
        return f"{base_name}-{form_name[:-2] if form_name.endswith('n') else form_name}"
    return f"{base_name}-{form_name}"


def forme_label(form_name: str) -> str:
    if not form_name:
        return ""
    if form_name.startswith("Mega ") and form_name.endswith(" X"):
        return "Mega-X"
    if form_name.startswith("Mega ") and form_name.endswith(" Y"):
        return "Mega-Y"
    if form_name.startswith("Mega "):
        return "Mega"
    if form_name.endswith(" Forme"):
        return form_name[:-6]
    if form_name.endswith(" Form"):
        return form_name[:-5]
    return form_name


def build_pokedex():
    base_paths = [
        PBS / "pokemon.txt",
        PBS / "pokemon_base_Gen_9_Pack.txt",
    ]
    form_paths = [
        PBS / "pokemon_forms.txt",
        PBS / "pokemon_forms_Gen_9_Pack.txt",
    ]

    bases_raw = parse_pbs_species_files(base_paths)
    base_map = {}
    for sid, data in bases_raw:
        base_map[sid] = data
    bases = list(base_map.items())
    base_map = {}
    for sid, data in bases:
        base_map[sid] = data
    bases = list(base_map.items())
    forms = parse_pbs_forms(form_paths)
    forms_by_species = defaultdict(list)
    for sid, fnum, fdata in forms:
        forms_by_species[sid].append((fnum, fdata))
    for sid in forms_by_species:
        forms_by_species[sid].sort(key=lambda x: x[0])

    pokedex = {}
    id_by_species = {}  # (SPECIES_ID, form_num) -> showdown id

    for dex_num, (sid, base) in enumerate(bases, start=1):
        entries = [(0, {}, base.get("FormName", ""))]
        for fnum, fdata in forms_by_species.get(sid, []):
            entries.append((fnum, fdata, fdata.get("FormName", f"Form {fnum}")))

        base_showdown_id = showdown_id(sid, entries[0][2] if entries[0][0] == 0 else "")
        base_display = display_name(
            sid, base, entries[0][2] if entries[0][0] == 0 else "",
            bool(entries[0][2]),
        )
        other_formes = []

        for fnum, fdata, form_name in entries:
            data = merge_form(base, fdata) if fnum else base
            is_form = bool(fnum or base.get("FormName"))
            name = display_name(sid, data, form_name or base.get("FormName", ""), is_form)
            entry_id = showdown_id(sid, form_name if fnum else base.get("FormName", ""))
            id_by_species[(sid, fnum)] = entry_id

            hp, atk, defense, spa, spd, spe, _bst = stats_from(data)
            t1, t2 = types_from(data)
            types = [t1] + ([t2] if t2 else [])

            abilities = {}
            ab_raw = data.get("Abilities", "")
            if ab_raw:
                ab_parts = [a.strip() for a in ab_raw.split(",") if a.strip()]
                if ab_parts:
                    abilities["0"] = title_name(ab_parts[0])
                if len(ab_parts) > 1:
                    abilities["1"] = title_name(ab_parts[1])
            ha = data.get("HiddenAbilities", "")
            if ha:
                abilities["H"] = title_name(ha.split(",")[0].strip())

            gender = GENDER_MAP.get(data.get("GenderRatio", "FemaleOneEighth"), {"M": 0.5, "F": 0.5})

            egg_groups = []
            for g in data.get("EggGroups", "").split(","):
                g = g.strip().upper()
                if g and g in EGG_GROUP_MAP:
                    egg_groups.append(EGG_GROUP_MAP[g])

            entry = {
                "num": dex_num,
                "name": name,
                "types": types,
                "genderRatio": gender,
                "baseStats": {
                    "hp": hp,
                    "atk": atk,
                    "def": defense,
                    "spa": spa,
                    "spd": spd,
                    "spe": spe,
                },
                "abilities": abilities,
                "heightm": float(data.get("Height", "1") or 1),
                "weightkg": float(data.get("Weight", "1") or 1),
                "color": title_name(data.get("Color", "Green")),
                "eggGroups": egg_groups,
                "gen": int(data.get("Generation", "9") or 9),
                "tier": "OU",
            }

            if data.get("Pokedex"):
                entry["desc"] = data["Pokedex"]

            if is_form:
                entry["baseSpecies"] = base_display
                entry["forme"] = forme_label(form_name or base.get("FormName", ""))
            else:
                entry["baseSpecies"] = name

            entry["spriteid"] = entry_id

            evos_raw = data.get("Evolutions", "")
            evo_list = parse_evolutions(evos_raw)
            if evo_list:
                evo_names = []
                for evo in evo_list:
                    target_data = base_map.get(evo["species"], {})
                    evo_names.append(display_name(evo["species"], target_data, "", False))
                entry["evos"] = evo_names
                if evo_list[0]["method"].lower() == "level":
                    try:
                        entry["evoLevel"] = int(evo_list[0]["param"])
                    except ValueError:
                        pass

            # prevo from reverse scan later
            pokedex[entry_id] = entry
            if is_form and name != base_display:
                other_formes.append(name)

        if other_formes and base_showdown_id in pokedex:
            pokedex[base_showdown_id]["otherFormes"] = other_formes
            pokedex[base_showdown_id]["formeOrder"] = [base_display] + other_formes

    # prevos
    for entry_id, entry in pokedex.items():
        for evo_name in entry.get("evos", []):
            evo_id = to_id(evo_name)
            if evo_id in pokedex:
                pokedex[evo_id]["prevo"] = entry["name"]
                if entry.get("evoLevel"):
                    pokedex[evo_id]["evoLevel"] = entry["evoLevel"]

    return pokedex, id_by_species


def build_moves():
    moves = {}
    for move_id, data in parse_pbs_blocks(PBS / "moves.txt"):
        name = data.get("Name", title_name(move_id))
        mid = to_id(name)
        category = data.get("Category", "Physical").capitalize()
        flags = {}
        for flag in data.get("Flags", "").split(","):
            flag = flag.strip()
            if not flag:
                continue
            key = flag[0].lower() + flag[1:]
            if key == "CanProtect":
                key = "protect"
            elif key == "CanMirrorMove":
                key = "mirror"
            elif key == "HighCriticalHitRate":
                key = "crit"
            elif key == "Sound":
                key = "sound"
            elif key == "Bomb":
                key = "bullet"
            else:
                key = to_id(key)
            flags[key] = 1

        entry = {
            "num": len(moves) + 1,
            "name": name,
            "type": title_type(data.get("Type", "NORMAL")),
            "category": category,
            "basePower": int(data.get("Power", "0") or 0),
            "accuracy": 100 if data.get("Accuracy", "100") == "0" else int(data.get("Accuracy", "100") or 100),
            "pp": int(data.get("TotalPP", "20") or 20),
            "priority": int(data.get("Priority", "0") or 0),
            "flags": flags,
            "desc": data.get("Description", ""),
            "shortDesc": data.get("Description", "")[:80],
            "gen": 9,
        }
        if entry["accuracy"] == 0:
            entry["accuracy"] = True
        moves[mid] = entry
    return moves


def build_abilities():
    abilities = {}
    for ab_id, data in parse_pbs_blocks(PBS / "abilities.txt"):
        name = data.get("Name", title_name(ab_id))
        aid = to_id(name)
        desc = data.get("Description", "")
        abilities[aid] = {
            "num": len(abilities) + 1,
            "name": name,
            "desc": desc,
            "shortDesc": desc[:80],
            "gen": 3,
        }
    return abilities


def build_learnsets(pokedex):
    base_paths = [
        PBS / "pokemon.txt",
        PBS / "pokemon_base_Gen_9_Pack.txt",
    ]
    form_paths = [
        PBS / "pokemon_forms.txt",
        PBS / "pokemon_forms_Gen_9_Pack.txt",
    ]
    bases_raw = parse_pbs_species_files(base_paths)
    base_map = {}
    for sid, data in bases_raw:
        base_map[sid] = data
    bases = list(base_map.items())
    forms = parse_pbs_forms(form_paths)
    forms_by_species = defaultdict(list)
    for sid, fnum, fdata in forms:
        forms_by_species[sid].append((fnum, fdata))

    learnsets = {}

    def add_moves(entry_id, moves_key, prefix):
        raw = data.get(moves_key, "")
        if not raw:
            return
        parts = [p.strip() for p in raw.split(",") if p.strip()]
        i = 0
        while i + 1 < len(parts):
            try:
                level = int(parts[i])
            except ValueError:
                i += 1
                continue
            move_name = title_name(parts[i + 1])
            move_id = to_id(move_name)
            learnsets[entry_id]["learnset"].setdefault(move_id, []).append(f"{prefix}{level}")
            i += 2

    def add_list(entry_id, key, tag):
        raw = data.get(key, "")
        if not raw:
            return
        for move_token in raw.split(","):
            move_token = move_token.strip()
            if not move_token:
                continue
            move_id = to_id(title_name(move_token))
            learnsets[entry_id]["learnset"].setdefault(move_id, []).append(tag)

    for sid, base in bases:
        entries = [(0, {}, "")]
        for fnum, fdata in forms_by_species.get(sid, []):
            entries.append((fnum, fdata, fdata.get("FormName", "")))

        for fnum, fdata, form_name in entries:
            data = merge_form(base, fdata) if fnum else base
            entry_id = showdown_id(sid, form_name if fnum else base.get("FormName", ""))
            if entry_id not in pokedex:
                continue
            learnsets[entry_id] = {"learnset": {}}
            add_moves(entry_id, "Moves", "9L")
            add_list(entry_id, "TutorMoves", "9T")
            add_list(entry_id, "EggMoves", "9E")

    return learnsets


def parse_encounters():
    path = PBS / "encounters.txt"
    maps = defaultdict(lambda: {"slots": []})
    map_id = None
    enc_type = None

    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.rstrip()
        if not line.strip() or line.startswith("#---") or line.startswith("# See"):
            continue
        m = re.match(r"^\[(\d+)(?:,(\d+))?\]\s*(?:#\s*(.*))?$", line.strip())
        if m:
            map_id = int(m.group(1))
            enc_type = None
            continue
        if map_id is None:
            continue
        stripped = line.strip()
        sm = re.match(r"^(\d+),([A-Z0-9_]+),(\d+)(?:,(\d+))?$", stripped)
        if sm and enc_type:
            maps[map_id]["slots"].append({
                "type": enc_type,
                "chance": int(sm.group(1)),
                "species": sm.group(2),
                "min": int(sm.group(3)),
                "max": int(sm.group(4) or sm.group(3)),
            })
            continue
        tm = re.match(r"^([A-Za-z]+)(?:,(\d+))?$", stripped)
        if tm:
            enc_type = tm.group(1)
    return maps


def method_label(enc_type: str) -> str:
    if enc_type in LAND_ENC_TYPES:
        if enc_type == "Cave":
            return "Cave"
        if enc_type == "RockSmash":
            return "Rock Smash"
        return "Land"
    if enc_type in FISH_ENC_TYPES:
        return enc_type.replace("Rod", " Rod")
    if enc_type in WATER_ENC_TYPES:
        return enc_type
    return enc_type


def rarity_label(chance: int) -> str:
    if chance > 20:
        return "Common"
    if chance >= 5:
        return "Uncommon"
    return "Rare"


def build_encounters(pokedex):
    map_names = parse_map_metadata()
    enc_maps = parse_encounters()
    by_species = defaultdict(list)

    for map_id, block in sorted(enc_maps.items()):
        map_name = map_names.get(map_id, f"Map {map_id:03d}")
        for slot in block["slots"]:
            sid = slot["species"]
            entry_id = showdown_id(sid, "")
            if entry_id not in pokedex and to_id(sid) in pokedex:
                entry_id = to_id(sid)
            levels = str(slot["min"]) if slot["min"] == slot["max"] else f"{slot['min']}-{slot['max']}"
            by_species[entry_id].append({
                "map": map_name,
                "mapId": map_id,
                "method": method_label(slot["type"]),
                "rarity": rarity_label(slot["chance"]),
                "chance": slot["chance"],
                "levels": levels,
            })

    for entry_id in by_species:
        by_species[entry_id].sort(key=lambda x: (x["map"], x["method"], -x["chance"]))
    return dict(by_species)


def build_search_index(pokedex, moves, abilities):
    index = []
    for pid in sorted(pokedex.keys()):
        index.append(f"{pid} pokemon")
    for mid in sorted(moves.keys()):
        index.append(f"{mid} move")
    for aid in sorted(abilities.keys()):
        index.append(f"{aid} ability")
    for t in (
        "normal", "fire", "water", "electric", "grass", "ice", "fighting", "poison",
        "ground", "flying", "psychic", "bug", "rock", "ghost", "dragon", "dark", "steel", "fairy",
    ):
        index.append(f"{t} type")
    index.sort()

    battle_index = []
    for row in index:
        parts = row.split(" ")
        battle_index.append(parts)

    count_index = {}
    for t in (
        "Normal", "Fire", "Water", "Electric", "Grass", "Ice", "Fighting", "Poison",
        "Ground", "Flying", "Psychic", "Bug", "Rock", "Ghost", "Dragon", "Dark", "Steel", "Fairy",
    ):
        tid = to_id(t)
        count_index[f"{tid} move"] = sum(1 for m in moves.values() if m["type"] == t)
        count_index[f"{tid} pokemon"] = sum(
            1 for p in pokedex.values() if t in p.get("types", [])
        )

    return {
        "BattleSearchIndex": battle_index,
        "BattleSearchIndexOffset": [""] * len(battle_index),
        "BattleSearchCountIndex": count_index,
        "BattleArticleTitles": {},
    }


def build_teambuilder_table(pokedex):
    ids = sorted(pokedex.keys())
    return {
        "tiers": [["header", "All Pokémon"], *ids],
        "overrideTier": {pid: "OU" for pid in ids},
        "items": [],
        "formatSlices": {"OU": len(ids) + 1},
        "learnsets": {},
    }


def build_typechart():
    # Gen 9 standard chart (simplified descriptions)
    chart = {}
    types = [
        "Normal", "Fire", "Water", "Electric", "Grass", "Ice", "Fighting", "Poison",
        "Ground", "Flying", "Psychic", "Bug", "Rock", "Ghost", "Dragon", "Dark", "Steel", "Fairy",
    ]
    for t in types:
        chart[t] = {"damageTaken": {}, "HPivs": {}}
    # Hand-tuned common matchups — full chart is large; Dex mainly needs keys to exist.
    matchups = {
        "Fire": {"Water": 2, "Grass": 0.5, "Ice": 0.5, "Fire": 0.5, "Ground": 2, "Rock": 2, "Bug": 0.5, "Steel": 0.5},
        "Water": {"Fire": 0.5, "Water": 0.5, "Grass": 2, "Ground": 2, "Rock": 2, "Dragon": 2},
        "Grass": {"Fire": 2, "Water": 0.5, "Grass": 0.5, "Poison": 2, "Ground": 0.5, "Flying": 2, "Bug": 2, "Dragon": 2, "Steel": 0.5},
        "Electric": {"Water": 0.5, "Electric": 0.5, "Grass": 2, "Ground": 0, "Flying": 0.5, "Dragon": 2},
        "Ice": {"Fire": 2, "Water": 0.5, "Grass": 2, "Ice": 0.5, "Ground": 2, "Flying": 2, "Dragon": 2, "Steel": 0.5},
        "Fighting": {"Normal": 0.5, "Ice": 2, "Poison": 0.5, "Flying": 2, "Psychic": 2, "Bug": 0.5, "Rock": 2, "Ghost": 0, "Dark": 0.5, "Steel": 2, "Fairy": 0.5},
        "Poison": {"Grass": 0.5, "Poison": 0.5, "Ground": 2, "Rock": 0.5, "Ghost": 0.5, "Steel": 0, "Fairy": 2},
        "Ground": {"Fire": 2, "Electric": 2, "Grass": 2, "Poison": 0.5, "Flying": 0, "Bug": 0.5, "Rock": 2, "Steel": 2},
        "Flying": {"Electric": 0.5, "Grass": 0.5, "Ice": 2, "Fighting": 0.5, "Ground": 0, "Bug": 0.5, "Rock": 2, "Steel": 0.5},
        "Psychic": {"Fighting": 0.5, "Poison": 0.5, "Psychic": 0.5, "Dark": 2, "Steel": 0.5},
        "Bug": {"Fire": 2, "Grass": 0.5, "Fighting": 0.5, "Poison": 0.5, "Flying": 2, "Psychic": 0.5, "Ghost": 0.5, "Dark": 0.5, "Steel": 0.5, "Fairy": 0.5},
        "Rock": {"Fire": 0.5, "Ice": 2, "Fighting": 0.5, "Ground": 2, "Flying": 0.5, "Bug": 2, "Steel": 2},
        "Ghost": {"Normal": 0, "Psychic": 0.5, "Ghost": 2, "Dark": 2},
        "Dragon": {"Ice": 2, "Dragon": 2, "Fairy": 2, "Steel": 0.5},
        "Dark": {"Fighting": 2, "Psychic": 0.5, "Ghost": 0.5, "Dark": 0.5, "Fairy": 2},
        "Steel": {"Fire": 2, "Water": 0.5, "Electric": 0.5, "Ice": 0.5, "Rock": 0.5, "Steel": 0.5, "Fairy": 0.5},
        "Fairy": {"Fire": 0.5, "Fighting": 0.5, "Poison": 2, "Dragon": 0, "Dark": 0.5, "Steel": 2},
        "Normal": {"Fighting": 2, "Ghost": 0},
    }
    for def_type, taken in matchups.items():
        entry = chart[def_type]
        for atk, mult in taken.items():
            if mult == 0:
                entry["damageTaken"][to_id(atk)] = 3
            elif mult == 0.5:
                entry["damageTaken"][to_id(atk)] = 2
            elif mult == 2:
                entry["damageTaken"][to_id(atk)] = 1
    return chart


def export_all(out_dir: Path):
    out_dir.mkdir(parents=True, exist_ok=True)
    pokedex, _ = build_pokedex()
    moves = build_moves()
    abilities = build_abilities()
    learnsets = build_learnsets(pokedex)
    encounters = build_encounters(pokedex)
    search = build_search_index(pokedex, moves, abilities)
    teambuilder = build_teambuilder_table(pokedex)
    typechart = build_typechart()

    write_js(out_dir / "pokedex.js", "BattlePokedex", pokedex)
    write_js(out_dir / "moves.js", "BattleMovedex", moves)
    write_js(out_dir / "abilities.js", "BattleAbilities", abilities)
    write_js(out_dir / "learnsets.js", "BattleLearnsets", learnsets)
    write_js(out_dir / "encounters.js", "BattleEncounters", encounters)
    write_js(out_dir / "typechart.js", "BattleTypeChart", typechart)
    write_js(out_dir / "items.js", "BattleItems", {})
    write_js(out_dir / "aliases.js", "BattleAliases", {})

    search_path = out_dir / "search-index.js"
    search_body = "// Auto-generated by tools/export_showdown_dex.py — do not edit\n\n"
    for key, val in search.items():
        search_body += f"exports.{key} = {json.dumps(val, separators=(',', ':'))};\n\n"
    search_path.write_text(search_body, encoding="utf-8")
    print(f"wrote {search_path} ({search_path.stat().st_size // 1024} KB)")

    tb_path = out_dir / "teambuilder-tables.js"
    tb_body = "// Auto-generated by tools/export_showdown_dex.py — do not edit\n\n"
    tb_body += f"exports.BattleTeambuilderTable = {es3_stringify(teambuilder)};\n"
    tb_path.write_text(tb_body, encoding="utf-8")
    print(f"wrote {tb_path} ({tb_path.stat().st_size // 1024} KB)")

    meta = {
        "species": len(pokedex),
        "moves": len(moves),
        "abilities": len(abilities),
        "encounterSpecies": len(encounters),
    }
    (out_dir / "meta.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    print(f"export complete: {meta}")


def main():
    ap = argparse.ArgumentParser(description="Export PBS data for Showdown-style dex website")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT, help="Output directory for JS data files")
    args = ap.parse_args()
    export_all(args.out)


if __name__ == "__main__":
    main()
